#Please use lowercase
vote:
  - '&a----------&f[&6Vote&f]&a----------'
  - '&aPlanetMinecruft: &chttp://poweredbyhate.net/'
  - '&aSwagDoritos: &chttp://poweredbyhate.net/'
  - '&aSpigotVotes: &chttp://poweredbyhate.net/'
  - '&a----------&f[&6Vote&f]&a----------'

discord:
  - '&aInvite Link: &7https://discord.gg/SvFEBGW'
laxwashere:
  - '&aLaxWasHere, yes'
electroniccat:
  - '&aLast known sighting:&c http://i.giphy.com/GFHJXPCoVQEec.gif'
